// foods.js - پایگاه داده جامع Nutrition OS (USDA FoodData Central + انستیتو تحقیقات تغذیه‌ای ایران)
window.MASTER_FOODS = [
  // ۱. غلات، نان‌ها و فرآورده‌های نشاسته‌ای
  {"id": "gr_1", "name": "برنج سفید کته کم‌روغن", "category": "grains_cooked", "state": "cooked", "calories": 130, "protein": 2.7, "carbs": 28.2, "fat": 0.3},
  {"id": "gr_2", "name": "برنج سفید آبکش مجلسی با روغن", "category": "grains_cooked", "state": "cooked", "calories": 165, "protein": 2.6, "carbs": 28.0, "fat": 4.8},
  {"id": "gr_3", "name": "برنج قهوه‌ای پخته", "category": "grains_cooked", "state": "cooked", "calories": 123, "protein": 2.7, "carbs": 25.6, "fat": 1.0},
  {"id": "gr_4", "name": "برنج سفید ایرانی خام", "category": "grains_raw", "state": "raw", "calories": 365, "protein": 7.1, "carbs": 80.0, "fat": 0.7},
  {"id": "gr_5", "name": "برنج قهوه‌ای دانه بلند خام (USDA)", "category": "grains_raw", "state": "raw", "calories": 362, "protein": 7.5, "carbs": 76.2, "fat": 2.7},
  {"id": "gr_6", "name": "نان سنگک سنتی سبوس‌دار", "category": "grains_cooked", "state": "cooked", "calories": 260, "protein": 9.0, "carbs": 50.0, "fat": 2.0},
  {"id": "gr_7", "name": "نان بربری سنتی", "category": "grains_cooked", "state": "cooked", "calories": 265, "protein": 8.8, "carbs": 52.0, "fat": 2.2},
  {"id": "gr_8", "name": "نان تافتون سنتی", "category": "grains_cooked", "state": "cooked", "calories": 270, "protein": 8.5, "carbs": 54.0, "fat": 2.0},
  {"id": "gr_9", "name": "نان لواش ماشینی نازک", "category": "grains_cooked", "state": "cooked", "calories": 275, "protein": 8.0, "carbs": 56.0, "fat": 1.8},
  {"id": "gr_10", "name": "نان تست سفید غنی‌شده", "category": "grains_cooked", "state": "cooked", "calories": 265, "protein": 8.9, "carbs": 49.0, "fat": 3.2},
  {"id": "gr_11", "name": "نان تست جو و سبوس‌دار", "category": "grains_cooked", "state": "cooked", "calories": 247, "protein": 12.0, "carbs": 42.0, "fat": 3.5},
  {"id": "gr_12", "name": "نان باگت فرانسوی", "category": "grains_cooked", "state": "cooked", "calories": 272, "protein": 9.2, "carbs": 53.0, "fat": 1.9},
  {"id": "gr_13", "name": "نان پیتا مدیترانه‌ای", "category": "grains_cooked", "state": "cooked", "calories": 275, "protein": 9.1, "carbs": 55.7, "fat": 1.2},
  {"id": "gr_14", "name": "نان جو رژیمی خالص", "category": "grains_cooked", "state": "cooked", "calories": 235, "protein": 10.5, "carbs": 45.0, "fat": 2.1},
  {"id": "gr_15", "name": "جو دوسر پرک کامل خام (USDA)", "category": "grains_raw", "state": "raw", "calories": 389, "protein": 16.9, "carbs": 66.3, "fat": 6.9},
  {"id": "gr_16", "name": "اوتمیل جو دوسر پخته با آب", "category": "grains_cooked", "state": "cooked", "calories": 71, "protein": 2.5, "carbs": 12.0, "fat": 1.5},
  {"id": "gr_17", "name": "کینوا سفید خام (USDA)", "category": "grains_raw", "state": "raw", "calories": 368, "protein": 14.1, "carbs": 64.2, "fat": 6.1},
  {"id": "gr_18", "name": "کینوا پخته شده", "category": "grains_cooked", "state": "cooked", "calories": 120, "protein": 4.4, "carbs": 21.3, "fat": 1.9},
  {"id": "gr_19", "name": "سیب‌زمینی خام با پوست (USDA)", "category": "grains_raw", "state": "raw", "calories": 77, "protein": 2.0, "carbs": 17.5, "fat": 0.1},
  {"id": "gr_20", "name": "سیب‌زمینی آب‌پز ساده", "category": "grains_cooked", "state": "cooked", "calories": 87, "protein": 1.9, "carbs": 20.1, "fat": 0.1},
  {"id": "gr_21", "name": "سیب‌زمینی تنوری / فرپز", "category": "grains_cooked", "state": "cooked", "calories": 93, "protein": 2.5, "carbs": 21.2, "fat": 0.1},
  {"id": "gr_22", "name": "سیب‌زمینی سرخ‌کرده خانگی", "category": "grains_cooked", "state": "cooked", "calories": 285, "protein": 3.4, "carbs": 37.0, "fat": 14.0},
  {"id": "gr_23", "name": "سیب‌زمینی شیرین خام (USDA)", "category": "grains_raw", "state": "raw", "calories": 86, "protein": 1.6, "carbs": 20.1, "fat": 0.1},
  {"id": "gr_24", "name": "سیب‌زمینی شیرین پخته", "category": "grains_cooked", "state": "cooked", "calories": 90, "protein": 2.0, "carbs": 20.7, "fat": 0.2},
  {"id": "gr_25", "name": "بلغور گندم خام", "category": "grains_raw", "state": "raw", "calories": 342, "protein": 12.3, "carbs": 75.8, "fat": 1.3},
  {"id": "gr_26", "name": "بلغور گندم پخته", "category": "grains_cooked", "state": "cooked", "calories": 83, "protein": 3.1, "carbs": 18.6, "fat": 0.2},
  {"id": "gr_27", "name": "بلغور جو خام", "category": "grains_raw", "state": "raw", "calories": 354, "protein": 12.5, "carbs": 73.5, "fat": 2.3},
  {"id": "gr_28", "name": "آرد گندم سفید نانوایی", "category": "grains_raw", "state": "raw", "calories": 364, "protein": 10.3, "carbs": 76.3, "fat": 1.0},
  {"id": "gr_29", "name": "آرد برنج مرغوب", "category": "grains_raw", "state": "raw", "calories": 366, "protein": 6.0, "carbs": 80.0, "fat": 1.4},
  {"id": "gr_30", "name": "آرد نخودچی خالص", "category": "grains_raw", "state": "raw", "calories": 387, "protein": 22.4, "carbs": 57.8, "fat": 6.7},
  {"id": "gr_31", "name": "پودر جوانه گندم خالص", "category": "grains_raw", "state": "raw", "calories": 385, "protein": 23.2, "carbs": 51.8, "fat": 9.7},
  {"id": "gr_32", "name": "سبوس برنج پودرشده", "category": "grains_raw", "state": "raw", "calories": 316, "protein": 13.4, "carbs": 49.7, "fat": 20.9},
  {"id": "gr_33", "name": "سبوس گندم خالص", "category": "grains_raw", "state": "raw", "calories": 216, "protein": 15.6, "carbs": 64.5, "fat": 4.3},
  {"id": "gr_34", "name": "کورن فلکس صبحانه ساده", "category": "grains_cooked", "state": "cooked", "calories": 378, "protein": 7.0, "carbs": 84.0, "fat": 0.9},

  // ۲. ماکارونی، پاستا و نودل
  {"id": "pas_1", "name": "اسپاگتی و ماکارونی سمولینا خام خشک", "category": "pasta_raw", "state": "raw", "calories": 371, "protein": 13.0, "carbs": 75.0, "fat": 1.5},
  {"id": "pas_2", "name": "اسپاگتی پخته آبکش ساده", "category": "pasta_cooked", "state": "cooked", "calories": 158, "protein": 5.8, "carbs": 31.0, "fat": 0.9},
  {"id": "pas_3", "name": "پاستا پنه خام خشک", "category": "pasta_raw", "state": "raw", "calories": 365, "protein": 12.5, "carbs": 74.5, "fat": 1.4},
  {"id": "pas_4", "name": "پاستا پنه پخته شده", "category": "pasta_cooked", "state": "cooked", "calories": 155, "protein": 5.5, "carbs": 30.5, "fat": 0.8},
  {"id": "pas_5", "name": "پاستا فرمی فوسیلی خام", "category": "pasta_raw", "state": "raw", "calories": 368, "protein": 12.8, "carbs": 74.8, "fat": 1.5},
  {"id": "pas_6", "name": "پاستا سبوس‌دار قهوه‌ای خام (USDA)", "category": "pasta_raw", "state": "raw", "calories": 348, "protein": 14.5, "carbs": 68.0, "fat": 2.5},
  {"id": "pas_7", "name": "پاستا سبوس‌دار پخته شده", "category": "pasta_cooked", "state": "cooked", "calories": 145, "protein": 6.5, "carbs": 28.5, "fat": 1.2},
  {"id": "pas_8", "name": "ورق لازانیا خشک خام", "category": "pasta_raw", "state": "raw", "calories": 360, "protein": 12.0, "carbs": 74.0, "fat": 1.6},
  {"id": "pas_9", "name": "ورق لازانیا آب‌پز شده", "category": "pasta_cooked", "state": "cooked", "calories": 140, "protein": 5.0, "carbs": 27.5, "fat": 0.9},
  {"id": "pas_10", "name": "نودل فوری خام خشک", "category": "pasta_raw", "state": "raw", "calories": 440, "protein": 9.5, "carbs": 62.0, "fat": 17.5},
  {"id": "pas_11", "name": "نودل فوری پخته با آب", "category": "pasta_cooked", "state": "cooked", "calories": 142, "protein": 3.2, "carbs": 21.0, "fat": 5.2},
  {"id": "pas_12", "name": "نودل برنجی آسیایی خام", "category": "pasta_raw", "state": "raw", "calories": 364, "protein": 3.4, "carbs": 83.0, "fat": 0.6},
  {"id": "pas_13", "name": "نودل برنجی پخته شده", "category": "pasta_cooked", "state": "cooked", "calories": 109, "protein": 1.0, "carbs": 25.0, "fat": 0.2},
  {"id": "pas_14", "name": "رشته سوپ ورمیشل خام", "category": "pasta_raw", "state": "raw", "calories": 370, "protein": 12.0, "carbs": 76.0, "fat": 1.2},
  {"id": "pas_15", "name": "رشته آش سنتی", "category": "pasta_raw", "state": "raw", "calories": 355, "protein": 11.5, "carbs": 73.0, "fat": 1.8},

  // ۳. حبوبات (خام و پخته تفکیک‌شده USDA)
  {"id": "leg_1", "name": "عدس سبز / قهوه‌ای خام (USDA)", "category": "legumes_raw", "state": "raw", "calories": 353, "protein": 25.8, "carbs": 60.1, "fat": 1.1},
  {"id": "leg_2", "name": "عدس آب‌پز پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 116, "protein": 9.0, "carbs": 20.1, "fat": 0.4},
  {"id": "leg_3", "name": "دال عدس قرمز خام", "category": "legumes_raw", "state": "raw", "calories": 345, "protein": 24.5, "carbs": 59.5, "fat": 1.0},
  {"id": "leg_4", "name": "دال عدس پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 112, "protein": 8.5, "carbs": 19.5, "fat": 0.4},
  {"id": "leg_5", "name": "نخود آبگوشتی درشت خام (USDA)", "category": "legumes_raw", "state": "raw", "calories": 364, "protein": 19.3, "carbs": 60.6, "fat": 6.0},
  {"id": "leg_6", "name": "نخود آب‌پز پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 164, "protein": 8.9, "carbs": 27.4, "fat": 2.6},
  {"id": "leg_7", "name": "لپه زرد خورشتی خام", "category": "legumes_raw", "state": "raw", "calories": 341, "protein": 24.5, "carbs": 60.0, "fat": 1.2},
  {"id": "leg_8", "name": "لپه پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 118, "protein": 8.3, "carbs": 21.0, "fat": 0.5},
  {"id": "leg_9", "name": "لوبیا چیتی خام (USDA)", "category": "legumes_raw", "state": "raw", "calories": 347, "protein": 21.4, "carbs": 62.5, "fat": 1.2},
  {"id": "leg_10", "name": "لوبیا چیتی آب‌پز ساده", "category": "legumes_cooked", "state": "cooked", "calories": 139, "protein": 9.7, "carbs": 25.1, "fat": 0.5},
  {"id": "leg_11", "name": "لوبیا قرمز کپسولی خام (USDA)", "category": "legumes_raw", "state": "raw", "calories": 333, "protein": 23.6, "carbs": 60.0, "fat": 0.8},
  {"id": "leg_12", "name": "لوبیا قرمز پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 127, "protein": 8.7, "carbs": 22.8, "fat": 0.5},
  {"id": "leg_13", "name": "لوبیا سفید آبگوشتی خام", "category": "legumes_raw", "state": "raw", "calories": 335, "protein": 23.0, "carbs": 61.0, "fat": 0.9},
  {"id": "leg_14", "name": "لوبیا سفید پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 139, "protein": 9.7, "carbs": 25.0, "fat": 0.4},
  {"id": "leg_15", "name": "لوبیا چشم‌بلبلی خام", "category": "legumes_raw", "state": "raw", "calories": 336, "protein": 23.5, "carbs": 60.0, "fat": 1.3},
  {"id": "leg_16", "name": "لوبیا چشم‌بلبلی پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 116, "protein": 7.7, "carbs": 21.0, "fat": 0.5},
  {"id": "leg_17", "name": "لوبیا سیاه خام (USDA)", "category": "legumes_raw", "state": "raw", "calories": 341, "protein": 21.6, "carbs": 62.4, "fat": 1.4},
  {"id": "leg_18", "name": "لوبیا سیاه پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 132, "protein": 8.9, "carbs": 23.7, "fat": 0.5},
  {"id": "leg_19", "name": "ماش سبز خام", "category": "legumes_raw", "state": "raw", "calories": 347, "protein": 23.8, "carbs": 62.6, "fat": 1.1},
  {"id": "leg_20", "name": "ماش پخته شده", "category": "legumes_cooked", "state": "cooked", "calories": 105, "protein": 7.0, "carbs": 19.1, "fat": 0.4},
  {"id": "leg_21", "name": "باقلا خشک زرد خام", "category": "legumes_raw", "state": "raw", "calories": 341, "protein": 26.1, "carbs": 58.3, "fat": 1.5},
  {"id": "leg_22", "name": "باقلا سبز پوست‌کنده خام", "category": "legumes_raw", "state": "raw", "calories": 88, "protein": 7.9, "carbs": 15.0, "fat": 0.7},
  {"id": "leg_23", "name": "باقلا سبز پخته با نمک", "category": "legumes_cooked", "state": "cooked", "calories": 110, "protein": 7.6, "carbs": 19.5, "fat": 0.5},
  {"id": "leg_24", "name": "دانه سویا روغنی خام (USDA)", "category": "legumes_raw", "state": "raw", "calories": 446, "protein": 36.5, "carbs": 30.2, "fat": 19.9},
  {"id": "leg_25", "name": "دانه سویا آب‌پز شده", "category": "legumes_cooked", "state": "cooked", "calories": 173, "protein": 16.6, "carbs": 9.9, "fat": 9.0},
  {"id": "leg_26", "name": "سویا بافت‌دار گوشتی خشک", "category": "legumes_raw", "state": "raw", "calories": 335, "protein": 51.5, "carbs": 31.0, "fat": 1.2},

  // ۴. پروتئین‌ها، گوشت، مرغ، ماهی و تخم‌مرغ (USDA SR Legacy)
  {"id": "usda_p1", "name": "سینه مرغ بدون پوست و استخوان خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 120, "protein": 22.5, "carbs": 0, "fat": 2.6},
  {"id": "usda_p2", "name": "سینه مرغ گریل / آب‌پز رژیمی پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 165, "protein": 31.0, "carbs": 0, "fat": 3.6},
  {"id": "usda_p3", "name": "سینه مرغ با پوست کامل خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 172, "protein": 20.9, "carbs": 0, "fat": 9.3},
  {"id": "usda_p4", "name": "سینه مرغ با پوست کباب‌شده پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 197, "protein": 29.8, "carbs": 0, "fat": 7.8},
  {"id": "usda_p5", "name": "فیله مرغ بدون چربی خام", "category": "protein_raw", "state": "raw", "calories": 110, "protein": 23.0, "carbs": 0, "fat": 1.8},
  {"id": "usda_p6", "name": "فیله مرغ گریل‌شده پخته", "category": "protein_cooked", "state": "cooked", "calories": 155, "protein": 31.5, "carbs": 0, "fat": 2.5},
  {"id": "usda_p7", "name": "ران مرغ بدون پوست کامل خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 145, "protein": 19.5, "carbs": 0, "fat": 7.2},
  {"id": "usda_p8", "name": "ران مرغ بدون پوست پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 190, "protein": 24.5, "carbs": 0, "fat": 9.5},
  {"id": "usda_p9", "name": "ساق ران مرغ بدون پوست پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 172, "protein": 28.3, "carbs": 0, "fat": 5.7},
  {"id": "usda_p10", "name": "مغز ران مرغ بدون پوست پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 209, "protein": 26.0, "carbs": 0, "fat": 10.9},
  {"id": "usda_p11", "name": "بال مرغ با پوست پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 290, "protein": 27.0, "carbs": 0, "fat": 19.5},
  {"id": "usda_p12", "name": "جگر مرغ تازه خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 119, "protein": 16.9, "carbs": 0.7, "fat": 4.8},
  {"id": "usda_p13", "name": "سنگدان مرغ پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 145, "protein": 27.0, "carbs": 0, "fat": 3.5},
  {"id": "usda_p14", "name": "سینه بوقلمون بدون پوست خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 111, "protein": 24.6, "carbs": 0, "fat": 0.7},
  {"id": "usda_p15", "name": "سینه بوقلمون پخته گریل (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 147, "protein": 30.1, "carbs": 0, "fat": 2.1},
  {"id": "usda_p16", "name": "ران بوقلمون بدون پوست پخته (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 170, "protein": 28.5, "carbs": 0, "fat": 5.5},
  {"id": "usda_p17", "name": "گوشت چرخ‌کرده بوقلمون ۹۳٪ خالص خام", "category": "protein_raw", "state": "raw", "calories": 149, "protein": 21.0, "carbs": 0, "fat": 7.0},
  {"id": "usda_p18", "name": "گوشت چرخ‌کرده سینه مرغ ۹۹٪ خام", "category": "protein_raw", "state": "raw", "calories": 112, "protein": 23.5, "carbs": 0, "fat": 1.5},
  {"id": "usda_p19", "name": "راسته گوساله ممتاز بدون چربی خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 135, "protein": 22.0, "carbs": 0, "fat": 4.8},
  {"id": "usda_p20", "name": "راسته گوساله استیک گریل (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 205, "protein": 29.5, "carbs": 0, "fat": 8.5},
  {"id": "usda_p21", "name": "فیله گوساله بدون چربی خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 125, "protein": 23.5, "carbs": 0, "fat": 3.2},
  {"id": "usda_p22", "name": "فیله گوساله پخته آب‌پز (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 195, "protein": 32.0, "carbs": 0, "fat": 6.5},
  {"id": "usda_p23", "name": "ران گوساله پاک‌شده خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 138, "protein": 21.8, "carbs": 0, "fat": 5.0},
  {"id": "usda_p24", "name": "ران گوسفندی بدون استخوان خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 160, "protein": 20.5, "carbs": 0, "fat": 8.1},
  {"id": "usda_p25", "name": "ران گوسفندی چلوگوشتی پخته", "category": "protein_cooked", "state": "cooked", "calories": 255, "protein": 26.0, "carbs": 0, "fat": 16.5},
  {"id": "usda_p26", "name": "گوشت چرخ‌کرده ۹۰٪ گوساله خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 176, "protein": 20.0, "carbs": 0, "fat": 10.0},
  {"id": "usda_p27", "name": "گوشت چرخ‌کرده مخلوط گوساله و گوسفند خام", "category": "protein_raw", "state": "raw", "calories": 254, "protein": 17.2, "carbs": 0, "fat": 20.0},
  {"id": "usda_p28", "name": "گوشت چرخ‌کرده تفت‌داده بدون روغن", "category": "protein_cooked", "state": "cooked", "calories": 240, "protein": 24.5, "carbs": 2.0, "fat": 15.0},
  {"id": "usda_p29", "name": "گوشت شتر بدون چربی خام", "category": "protein_raw", "state": "raw", "calories": 114, "protein": 22.5, "carbs": 0, "fat": 2.0},
  {"id": "usda_p30", "name": "گوشت بلدرچین بدون پوست خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 119, "protein": 22.0, "carbs": 0, "fat": 3.0},
  {"id": "usda_f1", "name": "فیله ماهی سالمون اقیانوس اطلس خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 208, "protein": 20.4, "carbs": 0, "fat": 13.4},
  {"id": "usda_f2", "name": "ماهی سالمون گریل / بخارپز (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 240, "protein": 25.0, "carbs": 0, "fat": 14.5},
  {"id": "usda_f3", "name": "ماهی قزل‌آلا پرورشی رنگین‌کمان خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 138, "protein": 20.9, "carbs": 0, "fat": 5.4},
  {"id": "usda_f4", "name": "ماهی قزل‌آلا کباب‌شده در فر (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 185, "protein": 26.5, "carbs": 0, "fat": 8.2},
  {"id": "usda_f5", "name": "ماهی تیلاپیا فیله خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 96, "protein": 20.1, "carbs": 0, "fat": 1.7},
  {"id": "usda_f6", "name": "ماهی تن زردباله تازه خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 109, "protein": 24.4, "carbs": 0, "fat": 0.5},
  {"id": "usda_f7", "name": "ماهی کاد اقیانوس آرام خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 82, "protein": 17.8, "carbs": 0, "fat": 0.7},
  {"id": "usda_f8", "name": "ماهی شیر خلیج فارس خام", "category": "protein_raw", "state": "raw", "calories": 125, "protein": 21.0, "carbs": 0, "fat": 4.0},
  {"id": "usda_f9", "name": "ماهی سفید دریای خزر خام", "category": "protein_raw", "state": "raw", "calories": 110, "protein": 19.5, "carbs": 0, "fat": 3.0},
  {"id": "usda_f10", "name": "میگو دریایی خام پاک‌شده (USDA)", "category": "protein_raw", "state": "raw", "calories": 85, "protein": 20.1, "carbs": 0.2, "fat": 0.5},
  {"id": "usda_f11", "name": "میگو بخارپز / آب‌پز شده (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 99, "protein": 24.0, "carbs": 0.2, "fat": 0.3},
  {"id": "usda_e1", "name": "تخم‌مرغ کامل متوسط خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 143, "protein": 12.6, "carbs": 0.7, "fat": 9.5},
  {"id": "usda_e2", "name": "تخم‌مرغ آب‌پز سفت (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 155, "protein": 13.0, "carbs": 1.1, "fat": 11.0},
  {"id": "usda_e3", "name": "سفیده تخم‌مرغ خالص خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 52, "protein": 11.0, "carbs": 0.7, "fat": 0.2},
  {"id": "usda_e4", "name": "سفیده تخم‌مرغ آب‌پز سفت (USDA)", "category": "protein_cooked", "state": "cooked", "calories": 52, "protein": 11.0, "carbs": 0.7, "fat": 0.2},
  {"id": "usda_e5", "name": "زرده تخم‌مرغ خالص خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 322, "protein": 15.9, "carbs": 3.6, "fat": 26.5},
  {"id": "usda_e6", "name": "تخم بلدرچین کامل خام (USDA)", "category": "protein_raw", "state": "raw", "calories": 158, "protein": 13.0, "carbs": 0.4, "fat": 11.1},
  {"id": "sup_1", "name": "پروتئین وی ایزوله ۱۰۰٪ خالص", "category": "protein_raw", "state": "raw", "calories": 375, "protein": 88.0, "carbs": 3.0, "fat": 1.0},
  {"id": "sup_2", "name": "پروتئین وی کنسانتره ۸۰٪ ورزشی", "category": "protein_raw", "state": "raw", "calories": 405, "protein": 78.0, "carbs": 7.5, "fat": 6.0},
  {"id": "sup_3", "name": "پروتئین کازئین دیرجذب شبانه", "category": "protein_raw", "state": "raw", "calories": 360, "protein": 80.0, "carbs": 4.0, "fat": 1.5},

  // ۵. لبنیات، چربی‌ها و روغن‌های خوراکی (USDA)
  {"id": "dy_1", "name": "شیر گاو بدون چربی ۰.۵٪ (USDA)", "category": "dairy", "state": "cooked", "calories": 35, "protein": 3.4, "carbs": 4.9, "fat": 0.1},
  {"id": "dy_2", "name": "شیر گاو کم‌چرب ۱.۵٪", "category": "dairy", "state": "cooked", "calories": 46, "protein": 3.3, "carbs": 4.8, "fat": 1.5},
  {"id": "dy_3", "name": "شیر گاو پرچرب ۳٪", "category": "dairy", "state": "cooked", "calories": 61, "protein": 3.2, "carbs": 4.7, "fat": 3.3},
  {"id": "dy_4", "name": "شیر بادام بدون شکر رژیمی", "category": "dairy", "state": "raw", "calories": 15, "protein": 0.6, "carbs": 0.3, "fat": 1.2},
  {"id": "dy_5", "name": "شیر سویا ارگانیک ساده", "category": "dairy", "state": "cooked", "calories": 45, "protein": 3.8, "carbs": 2.5, "fat": 2.0},
  {"id": "dy_6", "name": "ماست کم‌چرب پاستوریزه ۱.۵٪", "category": "dairy", "state": "cooked", "calories": 55, "protein": 4.0, "carbs": 5.5, "fat": 1.5},
  {"id": "dy_7", "name": "ماست پرچرب سنتی ۴٪", "category": "dairy", "state": "cooked", "calories": 75, "protein": 3.8, "carbs": 5.2, "fat": 4.0},
  {"id": "dy_8", "name": "ماست یونانی ایسلندی پرپروتئین", "category": "dairy", "state": "cooked", "calories": 73, "protein": 10.0, "carbs": 3.8, "fat": 1.9},
  {"id": "dy_9", "name": "ماست چکیده موسیردار", "category": "dairy", "state": "cooked", "calories": 115, "protein": 7.5, "carbs": 6.0, "fat": 6.5},
  {"id": "dy_10", "name": "دوغ سنتی بدون گاز نعنایی", "category": "dairy", "state": "cooked", "calories": 28, "protein": 1.8, "carbs": 2.5, "fat": 1.0},
  {"id": "dy_11", "name": "کشک پاستوریزه غلیظ شیشه‌ای", "category": "dairy", "state": "cooked", "calories": 110, "protein": 9.5, "carbs": 6.5, "fat": 4.8},
  {"id": "dy_12", "name": "کشک خشک محلی سخت", "category": "dairy", "state": "raw", "calories": 360, "protein": 52.0, "carbs": 12.0, "fat": 10.0},
  {"id": "dy_13", "name": "پنیر فتا صبحانه پاستوریزه", "category": "dairy", "state": "cooked", "calories": 264, "protein": 14.2, "carbs": 4.1, "fat": 21.3},
  {"id": "dy_14", "name": "پنیر کوتاژ رژیمی کم‌نمک (USDA)", "category": "dairy", "state": "cooked", "calories": 98, "protein": 11.1, "carbs": 3.4, "fat": 4.3},
  {"id": "dy_15", "name": "پنیر لیقوان اصیل تبریز", "category": "dairy", "state": "cooked", "calories": 290, "protein": 15.5, "carbs": 1.5, "fat": 24.5},
  {"id": "dy_16", "name": "پنیر موزارلا پیتزا رنده‌شده", "category": "dairy", "state": "cooked", "calories": 300, "protein": 22.0, "carbs": 2.2, "fat": 22.5},
  {"id": "dy_17", "name": "پنیر گودا / چدار ورقی", "category": "dairy", "state": "cooked", "calories": 403, "protein": 24.9, "carbs": 1.3, "fat": 33.1},
  {"id": "dy_18", "name": "خامه صبحانه پاستوریزه ۳۰٪", "category": "dairy", "state": "cooked", "calories": 295, "protein": 2.5, "carbs": 3.8, "fat": 30.0},
  {"id": "ft_1", "name": "روغن زیتون فرابکر خالص (USDA)", "category": "fats", "state": "raw", "calories": 884, "protein": 0, "carbs": 0, "fat": 100.0},
  {"id": "ft_2", "name": "روغن کنجد پرس سرد", "category": "fats", "state": "raw", "calories": 884, "protein": 0, "carbs": 0, "fat": 100.0},
  {"id": "ft_3", "name": "روغن کانولا کلزا (USDA)", "category": "fats", "state": "raw", "calories": 884, "protein": 0, "carbs": 0, "fat": 100.0},
  {"id": "ft_4", "name": "روغن آفتابگردان مایع", "category": "fats", "state": "cooked", "calories": 884, "protein": 0, "carbs": 0, "fat": 100.0},
  {"id": "ft_5", "name": "روغن نارگیل خوراکی خالص (USDA)", "category": "fats", "state": "raw", "calories": 862, "protein": 0, "carbs": 0, "fat": 98.0},
  {"id": "ft_6", "name": "کره حیوانی پاستوریزه ۸۲٪ (USDA)", "category": "fats", "state": "cooked", "calories": 717, "protein": 0.9, "carbs": 0.1, "fat": 81.0},
  {"id": "ft_7", "name": "روغن حیوانی کرمانشاهی اصل", "category": "fats", "state": "cooked", "calories": 898, "protein": 0.2, "carbs": 0, "fat": 99.5},

  // ۶. میوه‌ها، سبزیجات و صیفی‌جات (USDA Foundation)
  {"id": "vg_1", "name": "خیار بوته‌ای با پوست (USDA)", "category": "vegetables", "state": "raw", "calories": 15, "protein": 0.7, "carbs": 3.6, "fat": 0.1},
  {"id": "vg_2", "name": "گوجه‌فرنگی قرمز تازه بوته‌ای (USDA)", "category": "vegetables", "state": "raw", "calories": 18, "protein": 0.9, "carbs": 3.9, "fat": 0.2},
  {"id": "vg_3", "name": "کاهو رسمی پیچ سالادی (USDA)", "category": "vegetables", "state": "raw", "calories": 15, "protein": 1.4, "carbs": 2.9, "fat": 0.2},
  {"id": "vg_4", "name": "اسفناج تازه برگ‌ریز خام (USDA)", "category": "vegetables", "state": "raw", "calories": 23, "protein": 2.9, "carbs": 3.6, "fat": 0.4},
  {"id": "vg_5", "name": "کلم بروکلی تازه خام (USDA)", "category": "vegetables", "state": "raw", "calories": 34, "protein": 2.8, "carbs": 6.6, "fat": 0.4},
  {"id": "vg_6", "name": "گل کلم سفید خام (USDA)", "category": "vegetables", "state": "raw", "calories": 25, "protein": 1.9, "carbs": 5.0, "fat": 0.3},
  {"id": "vg_7", "name": "هویج نارنجی خام (USDA)", "category": "vegetables", "state": "raw", "calories": 41, "protein": 0.9, "carbs": 9.6, "fat": 0.2},
  {"id": "vg_8", "name": "پیاز زرد یا قرمز خام (USDA)", "category": "vegetables", "state": "raw", "calories": 40, "protein": 1.1, "carbs": 9.3, "fat": 0.1},
  {"id": "vg_9", "name": "قارچ دکمه‌ای سفید خام (USDA)", "category": "vegetables", "state": "raw", "calories": 22, "protein": 3.1, "carbs": 3.3, "fat": 0.3},
  {"id": "vg_10", "name": "فلفل دلمه‌ای سبز یا رنگی (USDA)", "category": "vegetables", "state": "raw", "calories": 26, "protein": 1.0, "carbs": 6.0, "fat": 0.3},
  {"id": "vg_11", "name": "کدو سبز با پوست خام (USDA)", "category": "vegetables", "state": "raw", "calories": 17, "protein": 1.2, "carbs": 3.1, "fat": 0.3},
  {"id": "vg_12", "name": "بادمجان قلمی خام (USDA)", "category": "vegetables", "state": "raw", "calories": 25, "protein": 1.0, "carbs": 5.9, "fat": 0.2},
  {"id": "vg_13", "name": "کلم برگ سفید یا بنفش (USDA)", "category": "vegetables", "state": "raw", "calories": 25, "protein": 1.3, "carbs": 5.8, "fat": 0.1},
  {"id": "vg_14", "name": "سیر تازه بوته‌ای خام (USDA)", "category": "vegetables", "state": "raw", "calories": 149, "protein": 6.4, "carbs": 33.1, "fat": 0.5},
  {"id": "vg_15", "name": "کرفس تازه با ساقه و برگ", "category": "vegetables", "state": "raw", "calories": 16, "protein": 0.7, "carbs": 3.0, "fat": 0.2},
  {"id": "vg_16", "name": "سبزی خوردن تازه مخلوط", "category": "vegetables", "state": "raw", "calories": 28, "protein": 2.5, "carbs": 4.5, "fat": 0.5},
  {"id": "vg_17", "name": "کدو حلوایی تنبل پخته", "category": "vegetables", "state": "cooked", "calories": 26, "protein": 1.0, "carbs": 6.5, "fat": 0.1},
  {"id": "vg_18", "name": "لبو چغندر قرمز پخته", "category": "vegetables", "state": "cooked", "calories": 44, "protein": 1.7, "carbs": 10.0, "fat": 0.2},
  {"id": "vg_19", "name": "شلغم سفید آب‌پز", "category": "vegetables", "state": "cooked", "calories": 22, "protein": 0.7, "carbs": 4.8, "fat": 0.1},
  {"id": "vg_20", "name": "بامیه سبز خورشتی تازه", "category": "vegetables", "state": "raw", "calories": 33, "protein": 1.9, "carbs": 7.5, "fat": 0.2},
  {"id": "fr_1", "name": "سیب درختی تازه با پوست (USDA)", "category": "fruits", "state": "raw", "calories": 52, "protein": 0.3, "carbs": 13.8, "fat": 0.2},
  {"id": "fr_2", "name": "موز رسیده تازه (USDA)", "category": "fruits", "state": "raw", "calories": 89, "protein": 1.1, "carbs": 22.8, "fat": 0.3},
  {"id": "fr_3", "name": "پرتقال تامسون تازه (USDA)", "category": "fruits", "state": "raw", "calories": 47, "protein": 0.9, "carbs": 11.8, "fat": 0.1},
  {"id": "fr_4", "name": "نارنگی شیرین تازه", "category": "fruits", "state": "raw", "calories": 53, "protein": 0.8, "carbs": 13.3, "fat": 0.3},
  {"id": "fr_5", "name": "لیمو ترش سنگی زرد", "category": "fruits", "state": "raw", "calories": 29, "protein": 1.1, "carbs": 9.3, "fat": 0.3},
  {"id": "fr_6", "name": "لیمو شیرین تازه آبدار", "category": "fruits", "state": "raw", "calories": 43, "protein": 0.8, "carbs": 10.5, "fat": 0.1},
  {"id": "fr_7", "name": "هندوانه شیرین سرخ (USDA)", "category": "fruits", "state": "raw", "calories": 30, "protein": 0.6, "carbs": 7.6, "fat": 0.2},
  {"id": "fr_8", "name": "خربزه یا طالبی ایرانی", "category": "fruits", "state": "raw", "calories": 34, "protein": 0.8, "carbs": 8.2, "fat": 0.2},
  {"id": "fr_9", "name": "انگور سفید بی‌دانه", "category": "fruits", "state": "raw", "calories": 69, "protein": 0.7, "carbs": 18.1, "fat": 0.2},
  {"id": "fr_10", "name": "انگور یاقوتی سیاه", "category": "fruits", "state": "raw", "calories": 71, "protein": 0.7, "carbs": 18.5, "fat": 0.2},
  {"id": "fr_11", "name": "کیوی ترش و شیرین تازه (USDA)", "category": "fruits", "state": "raw", "calories": 61, "protein": 1.1, "carbs": 14.7, "fat": 0.5},
  {"id": "fr_12", "name": "توت‌فرنگی تازه گلخانه‌ای (USDA)", "category": "fruits", "state": "raw", "calories": 33, "protein": 0.7, "carbs": 7.7, "fat": 0.3},
  {"id": "fr_13", "name": "گیلاس سیاه یا آلبالو", "category": "fruits", "state": "raw", "calories": 63, "protein": 1.1, "carbs": 16.0, "fat": 0.2},
  {"id": "fr_14", "name": "هلو زعفرانی تازه", "category": "fruits", "state": "raw", "calories": 39, "protein": 0.9, "carbs": 9.5, "fat": 0.3},
  {"id": "fr_15", "name": "زردآلو قیسی تازه", "category": "fruits", "state": "raw", "calories": 48, "protein": 1.4, "carbs": 11.1, "fat": 0.4},
  {"id": "fr_16", "name": "گلابی اسپادانا شیرین", "category": "fruits", "state": "raw", "calories": 57, "protein": 0.4, "carbs": 15.2, "fat": 0.1},
  {"id": "fr_17", "name": "انار دانه سرخ شیرین ساوه", "category": "fruits", "state": "raw", "calories": 83, "protein": 1.7, "carbs": 18.7, "fat": 1.2},
  {"id": "fr_18", "name": "انجیر تازه سیاه یا زرد", "category": "fruits", "state": "raw", "calories": 74, "protein": 0.8, "carbs": 19.2, "fat": 0.3},
  {"id": "fr_19", "name": "آووکادو تازه هاوس (USDA)", "category": "fruits", "state": "raw", "calories": 160, "protein": 2.0, "carbs": 8.5, "fat": 14.7},
  {"id": "fr_20", "name": "گوجه‌سبز نوبرانه ترش", "category": "fruits", "state": "raw", "calories": 46, "protein": 0.7, "carbs": 11.4, "fat": 0.3},

  // ۷. خشکبار، مغزها و دانه‌ها (USDA)
  {"id": "nt_1", "name": "گردو مغز سفید ایرانی (USDA)", "category": "nuts", "state": "raw", "calories": 654, "protein": 15.2, "carbs": 13.7, "fat": 65.2},
  {"id": "nt_2", "name": "بادام درختی شیرین خام (USDA)", "category": "nuts", "state": "raw", "calories": 579, "protein": 21.2, "carbs": 21.6, "fat": 49.9},
  {"id": "nt_3", "name": "پسته خام رفسنجان (USDA)", "category": "nuts", "state": "raw", "calories": 560, "protein": 20.2, "carbs": 27.2, "fat": 45.3},
  {"id": "nt_4", "name": "بادام زمینی خام (USDA)", "category": "nuts", "state": "raw", "calories": 567, "protein": 25.8, "carbs": 16.1, "fat": 49.2},
  {"id": "nt_5", "name": "کره بادام زمینی ۱۰۰٪ خالص", "category": "nuts", "state": "raw", "calories": 588, "protein": 25.0, "carbs": 20.0, "fat": 50.0},
  {"id": "nt_6", "name": "تخمه کدو مرمری خام (USDA)", "category": "nuts", "state": "raw", "calories": 559, "protein": 30.2, "carbs": 10.7, "fat": 49.0},
  {"id": "nt_7", "name": "دانه چیا اعلا (USDA)", "category": "nuts", "state": "raw", "calories": 486, "protein": 16.5, "carbs": 42.1, "fat": 30.7},
  {"id": "nt_8", "name": "تخم کتان قهوه‌ای آسیاب‌شده", "category": "nuts", "state": "raw", "calories": 534, "protein": 18.3, "carbs": 28.9, "fat": 42.2},
  {"id": "nt_9", "name": "خرما مضافتی یا پیارم", "category": "nuts", "state": "raw", "calories": 280, "protein": 2.0, "carbs": 75.0, "fat": 0.3},
  {"id": "nt_10", "name": "کشمش آفتابی یا پلویی", "category": "nuts", "state": "raw", "calories": 299, "protein": 3.1, "carbs": 79.2, "fat": 0.5},

  // ۸. غذاها و خوراک‌های سنتی ایرانی (انستیتو تغذیه)
  {"id": "ir_1", "name": "خورشت قورمه‌سبزی جاافتاده با گوشت", "category": "iranian", "state": "cooked", "calories": 155, "protein": 8.5, "carbs": 6.5, "fat": 11.0},
  {"id": "ir_2", "name": "خورشت قیمه لپه با سیب‌زمینی", "category": "iranian", "state": "cooked", "calories": 168, "protein": 8.5, "carbs": 13.5, "fat": 9.0},
  {"id": "ir_3", "name": "خورشت فسنجان با مغز گردو", "category": "iranian", "state": "cooked", "calories": 260, "protein": 8.0, "carbs": 14.0, "fat": 20.0},
  {"id": "ir_4", "name": "کباب کوبیده سنتی گوسفندی (سیخ ۱۰۰g)", "category": "iranian", "state": "cooked", "calories": 270, "protein": 18.0, "carbs": 2.0, "fat": 22.0},
  {"id": "ir_5", "name": "جوجه‌کباب سینه زعفرانی", "category": "iranian", "state": "cooked", "calories": 175, "protein": 28.0, "carbs": 1.5, "fat": 6.5},
  {"id": "ir_6", "name": "جوجه‌کباب ران با کره", "category": "iranian", "state": "cooked", "calories": 215, "protein": 24.0, "carbs": 1.5, "fat": 12.5},
  {"id": "ir_7", "name": "زرشک‌پلو با مرغ کامل", "category": "iranian", "state": "cooked", "calories": 175, "protein": 10.5, "carbs": 22.0, "fat": 5.0},
  {"id": "ir_8", "name": "عدس‌پلو با کشمش و گوشت چرخ‌کرده", "category": "iranian", "state": "cooked", "calories": 195, "protein": 8.5, "carbs": 29.0, "fat": 4.8},
  {"id": "ir_9", "name": "لوبیاپلو با گوشت تکه‌ای", "category": "iranian", "state": "cooked", "calories": 180, "protein": 7.5, "carbs": 25.0, "fat": 5.5},
  {"id": "ir_10", "name": "کتلت گوشت و سیب‌زمینی خانگی", "category": "iranian", "state": "cooked", "calories": 230, "protein": 13.5, "carbs": 14.0, "fat": 14.0},
  {"id": "ir_11", "name": "کوکو سبزی با تخم‌مرغ و زرشک", "category": "iranian", "state": "cooked", "calories": 180, "protein": 7.5, "carbs": 8.0, "fat": 13.5},
  {"id": "ir_12", "name": "کشک بادمجان خانگی با نعناداغ", "category": "iranian", "state": "cooked", "calories": 148, "protein": 4.5, "carbs": 9.5, "fat": 10.5},
  {"id": "ir_13", "name": "آبگوشت دیزی سنتی (کوبیده گوشت و نخود)", "category": "iranian", "state": "cooked", "calories": 210, "protein": 14.0, "carbs": 18.0, "fat": 9.5},
  {"id": "ir_14", "name": "آش رشته با کشک و نعناداغ", "category": "iranian", "state": "cooked", "calories": 145, "protein": 5.2, "carbs": 22.0, "fat": 4.5},
  {"id": "ir_15", "name": "حلیم گندم با گوشت بدون شکر", "category": "iranian", "state": "cooked", "calories": 165, "protein": 8.5, "carbs": 24.0, "fat": 4.0},
  {"id": "ir_16", "name": "الویه مرغ با مایونز", "category": "iranian", "state": "cooked", "calories": 245, "protein": 8.5, "carbs": 16.0, "fat": 16.5}
];
